-- READ-ONLY schema export for the Supabase SQL Editor.
-- Only SELECTs on system catalogs: it changes nothing and reads no table data
-- (except the list of storage bucket names/settings).
-- Output: ONE text cell. Click the cell -> copy, or Export -> CSV, and save as schema.sql
--
-- Covers: enum types, sequences, tables (+identity/defaults), constraints, indexes,
-- RLS flags, policies, functions, triggers, views, realtime publication, storage buckets
-- and storage policies. It does NOT include auth users, row data, storage files,
-- edge functions or secrets.

with parts(ord, name, ddl) as (

  -- 0: enum types
  select 0, t.typname,
         format('create type public.%I as enum (%s);', t.typname,
                string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder))
  from pg_type t
  join pg_enum e on e.enumtypid = t.oid
  where t.typnamespace = 'public'::regnamespace
  group by t.typname

  union all
  -- 1: sequences
  select 1, c.relname, format('create sequence if not exists public.%I;', c.relname)
  from pg_class c
  where c.relnamespace = 'public'::regnamespace and c.relkind = 'S'
    and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype = 'i')

  union all
  -- 2: tables
  select 2, c.relname,
    format(E'create table public.%I (\n%s\n);', c.relname,
      (select string_agg(
          format('  %I %s%s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
            case a.attidentity when 'a' then ' generated always as identity'
                               when 'd' then ' generated by default as identity' else '' end,
            case when a.attgenerated = '' and ad.adbin is not null
                 then ' default ' || pg_get_expr(ad.adbin, ad.adrelid) else '' end,
            case when a.attnotnull then ' not null' else '' end),
          E',\n' order by a.attnum)
       from pg_attribute a
       left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
       where a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped))
  from pg_class c
  where c.relnamespace = 'public'::regnamespace and c.relkind in ('r', 'p')

  union all
  -- 3: primary keys / unique / check constraints
  select 3, conrelid::regclass::text || '.' || conname,
         format('alter table %s add constraint %I %s;', conrelid::regclass, conname, pg_get_constraintdef(oid))
  from pg_constraint
  where connamespace = 'public'::regnamespace and contype in ('p', 'u', 'c')

  union all
  -- 4: foreign keys
  select 4, conrelid::regclass::text || '.' || conname,
         format('alter table %s add constraint %I %s;', conrelid::regclass, conname, pg_get_constraintdef(oid))
  from pg_constraint
  where connamespace = 'public'::regnamespace and contype = 'f'

  union all
  -- 5: indexes not created by a constraint
  select 5, i.indexname, i.indexdef || ';'
  from pg_indexes i
  join pg_class ic on ic.relname = i.indexname and ic.relnamespace = 'public'::regnamespace
  join pg_index x on x.indexrelid = ic.oid
  where i.schemaname = 'public'
    and not exists (select 1 from pg_constraint k where k.conindid = x.indexrelid)

  union all
  -- 6: functions (public, not owned by an extension)
  select 6, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')',
         pg_get_functiondef(p.oid) || ';'
  from pg_proc p
  where p.pronamespace = 'public'::regnamespace and p.prokind in ('f', 'p')
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')

  union all
  -- 7: views
  select 7, c.relname,
         format('create or replace view public.%I as %s', c.relname, pg_get_viewdef(c.oid, true))
  from pg_class c
  where c.relnamespace = 'public'::regnamespace and c.relkind = 'v'

  union all
  -- 8: triggers on public tables
  select 8, t.tgname, pg_get_triggerdef(t.oid) || ';'
  from pg_trigger t
  join pg_class c on c.oid = t.tgrelid
  where c.relnamespace = 'public'::regnamespace and not t.tgisinternal

  union all
  -- 9: row level security flags
  select 9, c.relname,
         format('alter table public.%I enable row level security;', c.relname) ||
         case when c.relforcerowsecurity
              then format(E'\nalter table public.%I force row level security;', c.relname) else '' end
  from pg_class c
  where c.relnamespace = 'public'::regnamespace and c.relkind in ('r', 'p') and c.relrowsecurity

  union all
  -- 10: policies on public tables and on storage.objects
  select 10, p.schemaname || '.' || p.tablename || '.' || p.policyname,
         format('create policy %I on %I.%I as %s for %s to %s%s%s;',
                p.policyname, p.schemaname, p.tablename, lower(p.permissive), lower(p.cmd),
                array_to_string(p.roles, ', '),
                case when p.qual is not null then E'\n  using (' || p.qual || ')' else '' end,
                case when p.with_check is not null then E'\n  with check (' || p.with_check || ')' else '' end)
  from pg_policies p
  where p.schemaname = 'public' or (p.schemaname = 'storage' and p.tablename = 'objects')

  union all
  -- 11: storage buckets (settings only, no files)
  select 11, b.id,
         format('insert into storage.buckets (id, name, public) values (%L, %L, %s) on conflict (id) do nothing;',
                b.id, b.name, b.public::text)
  from storage.buckets b

  union all
  -- 12: realtime publication
  select 12, pt.tablename,
         format('alter publication supabase_realtime add table public.%I;', pt.tablename)
  from pg_publication_tables pt
  where pt.pubname = 'supabase_realtime' and pt.schemaname = 'public'

  union all
  -- 13: extensions (informational)
  select 13, e.extname, format('-- extension in use: %s %s', e.extname, e.extversion)
  from pg_extension e
)
select string_agg(ddl, E'\n\n' order by ord, name) as schema_sql
from parts;
